language: node_js
node_js:
- node
install: true
script:
- echo "Skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: FPcZMgiuxbaTUnyiBWQbx1LaoHsAgIUDBWlMthE0rvjfoJJ1Qf4BCn/vujHKMvRWcwcO6G28BkQTykL855Je8N0G/QFNFtWTbt74KFSVgAMKhB1sFVPWpISGG+iTNSa4OJvLf7LKJ44bKrkCygCMxdvfSWPcH/3cay026ipK/zfGZ0iRDx5aBikA8Ph5irvNmAjBwMiift5Bo75/KVWhmsLxcNK+Bem0vozdXIjgm8LXY7JJY6ROEjxqXRmN4sTpQl+6RXssbZAK7iWbWAaxxr+CDYFuZj8uefNHMK2EWYkuamqcUXebnITRtq714t8zxz8I3giQS9GDmAhhVm2l0CkXwMpHLtG41jrs9HLYoxFEtP6XBXJd6SrFFlEBq65PkQWM8NdgiDPJFPkIvOENa04Le6mYVUFIxvyDRI7Q9ric23Gt7GgrXWrJWV/8Jdtq9clk6AhUWAZK69lg+VfRCNBIuas2tnwHfUMVJ2U+ciUNPQomb4c3K6yHa8VogxqLJt2I71FU26d8pipy2TU34OqHoyPbey/0BzhfA+65NsbwitRVNGIVmuc20Hgys/UOSQHMwlswBvJHOpWIn63XE/vhwnnuxkWoQGHmiULt4vWw28v0vTQR/IIHZiyJZSRqdspPpMJLZU5HKRLel63Ra44GlYxb5pKMczW8R40avTo=
  app: StartDroneApp
  on:
    repo: nicbuitr/StartDroneApp
cache:
  directories:
  - node_modules
