language: node_js
node_js:
- node
install: true
script:
- echo "Skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: Mx22J4YoiwbBnZE3hJK+4JWN1rI7kmaiRuoyFawxqA3vAXaoRgLyxxBsIzCm9LzFO8mZ7ShCnEMuI2nfbH0cKqCXiy1SEhuSzGGSUF+k5Ay5ki1Uq9p+T9MAI0HFLccU9/quDctpJKthMyBxLA+ocwE60oKWC5dBEZvYHL7uF9CFLWIT5FdeeqIH25wOO4vUxs73h3vK77KISk6aJv+pQmHwo9xDCDLRoWqaF9r2ZkzHROdDNjQBdhorKZj6SNPJcU4+c9G+5yEutax29co2p54c9RpfTsKw9bOII8ok6eII7t4C4StFfpXkVORxGy/83Wi6i87fL56BGMeMZpJchXgXC9DDiVsOLx2edDdlInZbq+rMQ8/WXdrFNCZT7RblRrpY1fJMHA0ZC0kW4Z/b7llyouG5SKQVQzRLv0nu9FEvNb/jY86KNi9LaExYSYycGv3IRNBCRdY5jV1rM973nwU7syImuSOLPkuj3w9zCkMdH0lp4DkQ+sl0TXSTkbpl5Xe18Ynlso1mtyYptEnguiQJce4Bbp4OPUJjdUy0r2BPTK5dX11VK3bJEtI3MiItT8W1nMcPrKmFhEJS8NPEdQsWnG5zGMCdckcaEijXZz9ANebg9VZ7zJ8qFqELM8GHlm+jCntavMKkxisCurIdf3LJ5dKkBnlAOiwYzUlrGRE=
  app: StartDroneApp
  on:
    repo: nicbuitr/StartDroneApp
cache:
  directories:
  - node_modules
