language: node_js
node_js:
- node
install: true
script:
- echo "Skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: blPlEPTMZi2FlINFPiuflYmwAkgIuup23VwcrzGMjPeiRo9IepaUUna7s5TIwTZTLZ6lGgjQPwK6cdomGcpASAO/aLGpc3O9oEETliHiZZz9jKexo+UpNbYQSNgGvKhmpX8uk+sp/dJdm244QVf6J+P6PS00vGgpHlPkOg3WolSiKmMGa62+m56OznKl3nkbAwgw8vEo+ruGa6af/cFy4P3MecjVALxRm13UqgzvTUUOpHvWX8MMa9YQ5a/zlTHGoflpIWW7Q3zeNW7mg0Ojaxy4Fhfv/r77l8nH/OPhaAuWto7w1SFKFm0VQYuuz1rrPaw9UkT5F5RWJxc37y5+kbh8NljOQbY/xPChGqNP7/jIleOf7AHKnjytN4mnLlLepJBrM0Cb5478kON4cofq7sivgMGfEOjtNITcmLO8rLy8dFeT+uP/Es5lanVJfuuGp2/wGrQyCWrsaS8Hyl+YbNMr6ukkTHmsauI1PETrzMglsqo9XtlRPlr8FAs4hh8GWQ9IXYUCnXvjOMAUty2wXwKBGvAS9cXQU63vJUkFQRyJ5iwPz5ZIHAK/zbjpkvVrnhu2DCrPw2geTTnPbMyvu/lPP51dloXUAZ5HM3azsUXltCbZU+5zrmpZuZOYlPrtKV4WchZovYBr0yz2RfLNunSLS6raoBGm/OPYZKir48E=
  app: StartDroneApp
  on:
    repo: nicbuitr/StartDroneApp
cache:
  directories:
  - node_modules
