language: node_js
node_js:
- node
install: true
script:
- echo "Skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: S2h9xBqtr/qAUy5Oia2YxMZNZ8/ucvvW46UzfAzthv8hR9HUPU2PxVuJIpRJs8zjTSkDLWpCZKb2qIitGQDuKGWrRlXedaH40dnbBDxzT9R7l7b38qNcyyYaULwe0KGtz8Trh4eYhiTtc0KCB/KQMS+LZoiCAASCTvWCxRb11KnL3lvJKWkQCKsVmhvPMUC0mQMKaMtUhr1UPXhiOuA4LcXovgpIBNlvrm9gliegxhb+XBe1PoOBgppkPriT4lVUTyDNr++3n1+BJM0X/+ejdQ9vW41S1mogZ4+BvjGoBm5Wg/XGucn5xfGZQDjyxHQkURhOFo5rtcvVhKhG7X9uIiHSJpLDPY5CIPDCxkDC0tqjcJfWp6wpzhIuWMaAcpusBA8exmuR29q3MbHNdt/rJ912i0enNf/k7bUmIbDusHkSMNd7S1bSkxNFp8wHtszVnZNw3Z5sNG7xSPKEEd+lv6kAa81Ecj53c0xVuWQQZUHdg3daGHzfn5hXxLANf+4Pj81VVdP0IyXd/fvOBHwSVv6hqpDINJHtKZclMf0ttVTSLyYkpYJKgn+sbT0Qu8mo78p5Qmtxafp2Wz+9rhMvgSPGEYUEBJ8GmfHSFRPYpBH8K387VucjfZSj0aS1yY6Ou6TioWr6H0ZNTDqJAPZs+nyQ01cwsJJRHHt8cXMstNs=
  app: StartDroneApp
  on:
    repo: nicbuitr/StartDroneApp
cache:
  directories:
  - node_modules
