language: node_js
node_js:
- node
install: true
script:
- echo "Skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: hNvGELvdQMh99rYhvKGFfECNfsGiYG1nF+M5XxzmvD1PfXRkr+wJFiDvOYgKbV+VHIPoxgBWmC0doFGYxtvQqeqmmGxQWTUltFDkv+kHsZyIPA68IluOTnXuAoEicTMF0CuQXziqrilu0bMWgZ5RfqxsmlefCMOhyyj3hCJ6u4OK//P66wdht0kwOfVqt7GJXIi2qV7xVqHc2Dxq7XINC5O2Eg7c9c2BnezO4PJrBnaPwZFtespfH0djYaoHs/n0rGaSkrRnnB2yQDocPkV+VqNKkZP0j689lgXKIkOF1EPfA33q7kudZTDHy4P8FExExS+AUBC431U2UkK8KWZP8BWXQiv5YWbCxmqL8V5AG5HYrqG0jxUmxZH1BBvH1fB6dMTdp8Bvq8ErS6gj2DstiBPLaqANO2sLWFsN994/LZIkue/C1AYrVoBNHlpzm5ov0AezBis3uTVOMOTVCnRC7juRQLmyED9JhgXp2ltjovMTlU/M0PjIeKzuiwCshQdoc//1LHZ+NMYJtYShKY8FXw3t8H3EZGqGxWna9E8cYGvqqCLcclIdfY3R5sFWnPeGZdwIoevOVJKhk8yrTNggJ/IGny/MoPQRAUySGDiyT2YrSrq0E6B4NsPOwMFfujz2mAvAn4zUiDfeF8UWCQc9L+L+Jx3/Ez4UB0miQJqEs3k=
  app: StartDroneApp
  on:
    repo: nicbuitr/StartDroneApp
cache:
  directories:
  - node_modules
