language: node_js
node_js:
- node
install: true
script:
- echo "Skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: GrB8SP3aEsxg9geV6jD8ry59cp27Y37E88gPw6TBgI4Fg+wuSJXLqD1C/JTwN97visIElAWqhbnd2uHgUxUjfGK+JaYVLqgmGMqZ0FaHP8DiWElgebX0XZd289jwwX6EfqXFrcL7tHf52ML0Klr3nSaAAZ8VTFvnaZAxK40hguOCuw0W/iazqXHxPiHsuXnMDN71rzyGdmEzNK6TIqtWSGcMIFFQFB5Zsl9UASjRtglnHTISNMZyH4y0lBQe8VLWmzsh4jiX4b++ZDU16J2mvRUbNJS9r+mJxLlUD/CAKU6L7ShtOgQB0b12Rq2faNd4lkGElbgge5eIaTjsIxsVhjeRHMlGOIPF5U9bMFUcxuE86q2xhn5Ru6cvHuIG7axPhiUG03zFa7Z1EkT8Mw4Dlt+QX9HiD41K5gV/c4dpGifEcxXnyYhhUdFwarZP2717Shlwr96s2apVv6ujlMX1eOXwOnaBUhyOM3zmfUM0O1L3Mt/lBFhfpQ45W9NfwRoawuoyCIKILsPqq4LwjZazqGc2aSa7FD8l2W4HCD/QSrWyiHZExrUb2HVKvtYPRl396VOwcgG+jMmuqNmC/PmUmMcosFTFiu3eHOXoZ05c97E5fyJpzX5isrMvoO0YjC96rBrZ6qZn8GWVMzVY98JrRw6X05qm1hzQOH9p3c9aSbs=
  app: startdroneapp
  on:
    repo: nicbuitr/StartDroneApp
cache:
  directories:
  - node_modules
