language: node_js
node_js:
- node
install: true
script:
- echo "Skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: Dud7REBjc5/zxYUb4wBgw+MGzDVLxgt/h0OfYR2PcnQwPDd1Fl9+gcbOhx3no4rmeCF0IxZWNwt7zmLFpDi2Zb7q/CKFqD/+ZqmYvWpQYm9eLcGFTSpVNb3KUyhjBJGLNtvAfPilqIQ0RdURHkIGwL/dIXDLSS5IzUH7G7TPM9pr9L7kUwAsBb+faGryi4oNAzjX+drNvbLelJeyMHRJdgK51LQvTSTR5tBC9JLPOMQIvhASFDRRV9RCOWt7AtBLlzr583Udce1nyIxRwd3UQ36tmmtH4UrHge+o2GVC8N6QmDI3ba3eSnTSwufGDkmtlneamPVEqtScNn2b03h94VGpFRZgQTMByxSBumUPBcEkVkcXfqBas2wiggX0SfmOdCtXD7MsySafc5kN3oYFNN06sr/P+M4IAjvQRB492AhBU65ukeawBvB8IsM2puDXToeO98itVXhCUP4LZu7dHqQJwgyK3ECcsF+p8XXw1QKEpCr8erNLmSyZQYubqzea96tTPMMEhbOG/vgKNGxaG8OhE/m3Xf9f50tXEGFD6T2oYkLe3TXI6u/gngyOu5gFnsynosvMMI0ce4d9S0vNcItHTJ/XWnzu4rK+HF/CKjJURj66iJK5BB7a6Yu6/C0/KkizOOzCtsCMAKG7vpgrL/rkk+typFmg4xlwIHlmq6s=
  app: startdronedpp
  on:
    repo: nicbuitr/StartDroneApp
cache:
  directories:
  - node_modules
