language: node_js
node_js:
- node
install: true
script:
- echo "Skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: KEQXJXbJ7HDOB2t0X2KtdkUxQzQ2quCk/AJgL6++32HfkUEZktTbbUpDZzJqEeWbFbqRYZwrbY4pnoVS9qWezBzfvReu+LKsjXiCKWfpZRYjxifJDO10lduwrAy1qTjwd65nknHdJ2dOYhNvLCc0fFbv5Sc6ZipfgqZ8KV08jhnqWcy0tPadxssN0vZRexC5SS8J4m8Fm40EKbRAx/Ql0gt/SwFPyV49Jd+g/zQn2/Xv6SWq6NyQfQkelThMjbKWSZ4kRKkEpBEdjOlqgujORhJTe17XImySyAKewL8oQy6UatiCwZNXzWWV2T6Hz0MsFQZ9LWJFA4FGFBONW/mtkiwarvTLFRuA4EGpWOdpivwSWpejjPhpvjDWx8NVQLC+ux5MfodFsJo0/eE/Uv/XbrV3jNl0mfUMMpCj38c1q1bDHycwVXHdqeWJxzwV1FnLqqpFBsVFl1qIqaUT1XbgqkuMt7i3gp9W0CzDPmWi7Q+AOTvJFIb6VC6e1HnPBpLVLn2KZiAFTZZBUGVe/NqwQbToUxo9NERW3Mb/vGfkAWqBhCljLyeiu7PTAEJM9zAs2MJw0+Uls765JbGHsGZnJhMUrlWz3cXDGwohxp1moDuunIXS2BxOmLVR31bw4yRoZMEisl/igmCf93XfOkgzL/nu6S/zBFT+NddKrWDbMxM=
  app: StartDroneApp
  on:
    repo: nicbuitr/StartDroneApp
cache:
  directories:
  - node_modules
