language: node_js
node_js:
- node
install: true
script:
- echo "Skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: "GC/qxWWHAQ/DT7pUwJB/YPfiwTbKDAz0gXYTkybaZDaangCgsfczi1hdB2je0MiAMpooCdHr8HDSEkVkGhEzbaVmQLL0OPWH2x4vbZqIPtQ2l8/9L1r6Fu8s4q+iPD5tgblvDhxuyaf7pTckzC1HNguGGRgrFnXWQh/2pXow6WaxUu5TDDyu+pdEilZ+D7rkUImJXH4LfX1VU1BCfmI/AKpBpOc+tBhDlIx4clh6CAnDWIZr+QVR3UMrMOpHzC/6xqyJQesEPbeqb0coAAp4L4ckFxrbxCnSoUnHaFtj8lBl1upbIu1gNuQnPNerH21nx9xCkk1BjJt8uyuIgZ/qUzhR/Rqgasor0a+7dghlg+uFI8Z/JUjBvCr29z7tzFp53gk24Zh/EXBGQVO++XARYecLCeWHD0prVAoaf/HG7j/LgFIYHjq1Lfiws2RNRcln4yNAvu+ADLEMEwmEEQXKSk9N+7vpOlpEX80P7hItDrfwsRxN7r/L3gu4KTSUCAqNqPa0JW/kUzGlj0vcnJLtWDybb4ojxt9dfgEy0q94py0IvPA6a5reZH/FpvBH/8sWZ4c3v/C3XQq6HfLR21qU3X9GGgLolOxWDDggGmjjGAI5oxmEx4tJluvJAW1DUre3C393/fGDbjrqjwjrSJN8klgTXJSxsv9ZKrYH3UY0cP0="
  app: StartDroneApp
  on:
    repo: nicbuitr/StartDroneApp
cache:
  directories:
  - node_modules
