language: node_js
node_js:
- node
install: true
script:
- echo "Skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: SWBI8SmUwJl0Ng/6N4C8jxhJly1OKYFZMtxZC4+qevfhByydIgASStdzYYYPo8suZu0uiOKI6bEJbVtUM8laWSNmCX3d3oLTXlxPBMPaaKLMrptr1aXKn3bh8/xohl0fte/iwtoo+5LLfPGfbEegKbxmEi6TVBM9th/tWBk0+QsJCnOet2wa9PGstjAOjC+GkORstRfq/MsQiQLXPC0A6KcFcI5G/HkmBKB/g3MqSFFlFdFhw1ZeRZg283E4+y7ElpD1YEjgq9CJr7pgK2QicT/StOwoeHWF9JPCuoR+kYxO7oY0DtAlUIQYoMuNdLoBEyNx8e/gFVY9JDJtMXA0MUCgKPUzuozqdH+ufjShlE5Mf3AZEB9Riawl4LHCK4oq0TIo/2eCA4ogCDpfbb+uIdGD0Yx5E5BxqfE7bXj8Sm30aXcQxys7ovFyWalallgYrBFCbyA3rJgU56Enl6QyHUP+oBM5XwOswQTlbv2/QnrQo6Du/kFubQ1lIuDVSvykkkpwkhhyrIQCWyoUCC5cs0GNuMag/yuzRZo3854q+zCR+WkwdG8oNDc1ToDiY/IowC9rJD1tZVURBWtEAszAA3kLbtOxE2b3Bt4/+O/5tL5YTgTOi7cj2HAHDdMNIq99cqdcXNqoEMnhXeHQu/SGIufXQGGx+K6ZBf7liNXka40=
  app: StartDroneApp
  on:
    repo: nicbuitr/StartDroneApp
cache:
  directories:
  - node_modules
